---
- name: Ansible Provision
  hosts: all
  tasks:
  - name: general settings
    block:
    - name: install tzdata
      apk:
        name:
          - tzdata
    - debug: var=timezone
    - name: change timezone setting
      file:
        src: /usr/share/zoneinfo/{{ timezone }}
        dest: /etc/localtime
        state: link
        force: yes
    - name: install container-dependencies
      apk:
        name:
          - runit
          - drill
          - bind-tools
          - su-exec
        state: installed
    - name: install build-dependencies
      apk:
        name:
          - build-base
          - linux-headers
          - automake
          - autoconf
          - libtool
          - git
          - tar
          - go
        state: installed
    - name: install unbound-dependencies
      apk:
        name:
          - libevent-dev
          - fstrm-dev
          - protobuf-c-dev
          - ldns-dev
          - libressl-dev
          - dnssec-root
          - expat-dev
          - python2-dev
          - swig
          - openssl
        state: installed
  - name: install unbound
    block:
    - debug: var=unbound_version
    - name: create unbound group
      group:
        name: "{{ unbound_user }}"
        system: yes
        state: present
    - name: create unbound user
      user:
        name: "{{ unbound_user }}"
        comment: "unbound server"
        group: "{{ unbound_user }}"
        system: yes
        shell: /sbin/nologin
    - name: create unbound directory
      file:
        path: "{{ unbound_root }}"
        state: directory
    - name: download unbound tarball
      get_url:
        url: "https://www.nlnetlabs.nl/downloads/unbound/unbound-{{ unbound_version }}.tar.gz"
        dest: "{{ unbound_root }}/unbound-{{ unbound_version }}.tar.gz"
    - name: extract unbound tarball
      unarchive:
        src: "{{ unbound_root }}/unbound-{{ unbound_version }}.tar.gz"
        dest: "{{ unbound_root }}/"
        copy: no
    - name: configure unbound
      shell: |
        ./configure \
        --prefix={{ unbound_root }} \
        --with-username={{ unbound_user }} \
        --with-run-dir="" \
        --with-pidfile="" \
        --localstatedir=/var \
        --with-rootkey-file=/usr/share/dnssec-root/trusted-key.key \
        --with-libevent \
        --with-pthreads \
        --disable-static \
        --disable-rpath \
        --with-ssl \
        --without-pythonmodule \
        --with-pyunbound \
        --enable-dnstap
      args:
        chdir: "{{ unbound_root }}/unbound-{{ unbound_version }}/"
    - name: build unbound
      make:
        chdir: "{{ unbound_root }}/unbound-{{ unbound_version }}/"
    - name: install unbound
      make:
        chdir: "{{ unbound_root }}/unbound-{{ unbound_version }}/"
        target: install
    - name: build golang-dnstap
      shell: |
        go get -u -v github.com/dnstap/golang-dnstap
        go get -u -v github.com/dnstap/golang-dnstap/dnstap
        go get -u -v github.com/farsightsec/golang-framestream
      environment:
        GOPATH: "{{ unbound_root }}"
    - name: remove source files
      file:
        path: "{{ item }}"
        force: yes
        state: absent
      with_items:
        - "{{ unbound_root }}/unbound-{{ unbound_version }}"
        - "{{ unbound_root }}/unbound-{{ unbound_version }}.tar.gz"
        - "{{ unbound_root }}/src"
        - "{{ unbound_root }}/pkg"
    - name: create device directory
      file:
        path: "{{ unbound_root }}/dev" 
        state: directory
    - name: make devices
      shell: |
        mknod {{ unbound_root }}/dev/random c 1 8 \
        && mknod {{ unbound_root }}/dev/log c 1 3
    - name: remove build-dependencies package
      apk:
        name:
          - build-base
          - linux-headers
          - automake
          - autoconf
          - libtool
          - git
          - tar
          - go
        state: absent
    - name: clean unbound directory
      file:
        path: "{{ unbound_root }}/share"
        state: absent
        force: true
    - name: create unbound directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ unbound_user }}"
        group: "{{ unbound_user }}"
      with_items:
        - "{{ unbound_root }}/var/run"
        - "{{ unbound_root }}/var/unbound"
