---
version: "3"
services:
  unbound:
    image: autechgemz/unbound:latest
    container_name: unbound
    restart: always
    healthcheck:
      test: ["CMD","drill","-o","rd","@localhost","localhost"]
      interval: 5m
      timeout: 10s
      retries: 3
