apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: unbound
spec:
  selector:
    matchLabels:
     app: unbound
  replicas: 2
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: autechgemz/unbound:latest
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP 
