kind: Service
apiVersion: v1
metadata:
  name: unbound
spec:
  selector:
    app: unbound 
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53 
    targetPort: 53 
  - name: dns-udp
    protocol: UDP 
    port: 53 
    targetPort: 53 
